### ISSUE TITLE
ncids-js module bundling 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1227]
We need to look into how we are building `ncids-js` and how packages are bundled and exported. Ideally, apps should only be getting the component code for js components that are specifically being imported. 

Look at webpack, tree shaking, es modules, etc.

**Comment by bryanpizzillo** [comment]
IDK about tree shaking, but we should be doing `import nciHeader from @nciocpl/ncids-js/components/nci-header/extended` or some such instead of `import {nciHeaderWithStuff} from @nciocpl/ncids-js`. Tree shakings and things requires potentially different configs, if even possible. At the end of the day the `@nciocpl/ncids-js/index` module contains all the things.

**Comment by bryanpizzillo** [comment]
Yeah, so we had the discussion again and came to the same conclusions. Technically the folders have changed since our last discussion. This also affects generating documentation.
