### ISSUE TITLE
Update documentation site Border page content to use Utility page template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1505]
### Request Description
This change request is update the Border page on the NCIDS from only having basic information about border tokens to using our Utility page template.

- [ ] IA/development/design updates to the [Border doc site page](https://designsystem-dev.cancer.gov/develop/foundations/appearance/border) with all content needed using the new utility page template (created in #1593)
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt the border utilities within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use border utilities/tokens without pointing to USWDS
- The community Figma file will be updated to include the border utilities/tokens
- The NCIDS code will be updated to fully adopt the border utilities/tokens

### What's the current functionality?
- The doc site directs users to USWDS [Border](https://designsystem.digital.gov/utilities/border/) utility page

### Related Tickets
* **Prerequisite:** #1593 
* Original story: #1199 
* Related story: #1327

**Comment by dlescarbeau** [comment]
Approach:
My thought here is that we should create two new display table components.

One will display a required class name, and display an optional value, an optional example, or both. This would be used for `border`, `border-radius`, and `border-width` tables, similar to [USWDS](https://designsystem.digital.gov/utilities/border/).
- Additionally, these tokens should be broken up into groups similar to our updated color foundations page.
- (I could maybe see us abstracting the TextDemonstration table component to just display a class name, value, and example and using that here, but that'd likely be more trouble than just creating another table display component in the factory).

The other will display color chips preceding the displayed class name as examples of the border colors, as well as an optional color value (like `gray-5`) and required hex value. This would be used for the `border color` table, showing an example color chip as well as the color value and hex value of the token. Once again, can reference [USWDS](https://designsystem.digital.gov/utilities/border/).

**Comment by bryanpizzillo** [comment]
@dlescarbeau can you please add a note of which utility modules should be added to this page, and which table would be used. Like, be VERY clear about what you are going to do here. e.g., "I could maybe see us abstracting the TextDemonstration table component" is not telling me what you want for that.

**Comment by dlescarbeau** [comment]
Tasks:

[ ] Create a BorderDisplayTable component. The component will display:
Column 1 - Class Name (from JSON ?)
  - grid-col-auto maybe? (should fill the table with the other columns being set)
*Optional Column 2 - Pixel value of border (not necessary for border-top, bottom, x, y, left, right, therefore optional)
  - likely grid-col-1, just a pixel value
Column 2 (or 3) - An example of the border, IE a box with the border being displayed (see [USWDS Border](https://designsystem.digital.gov/utilities/border/))
  - grid-col-2 most likely depending on the border example

[ ] Create a BorderColorDisplayTable component. The component will display:
Column 1 - Border example color chip with light background (should be a 1px solid border with the specified color)
  - grid-col-1
Column 2 - Border example color chip with dark background (same as above but dark background)
  - grid-col-1
Column 3 - Class Name (from JSON) displayed as text with gray "code" background
  - grid-col-auto (should fill the table with the other columns being set)
Column 4 - Token value, should be displayed as text with the gray "code" background
  - grid-col-2 most likely
Column 5 - Color example with hex value, just like the color examples of the color docs page. (We may want to consider this color example with the color and hex value as a re-useable component to be shared amongst pages with colors? Something to consider but otherwise is just an example of the color with the hex value next to it.
  - likely fits better in grid-col-2

[ ] Add `border`, `border-radius`, `border-color`, `border-style`, and `border-width` utilities from utility-modules.json
  - border, border-radius, border-style, and border-width will all use the BorderDisplayTable
  - border-color will use the BorderColorDisplayTable

**Comment by bryanpizzillo** [comment]
This ticket should come before Height/Width, Circle, Outline.
