### ISSUE TITLE
CR: Adopt documentation site Opacity page to NCIDS ownership

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1507]
### Request Description
This change request is to fully adopt opacity tokens within the NCIDS from being a pointer to USWDS to our full ownership. This change will require:

- [ ] IA/design updates to the [Opacity doc site page](https://designsystem-dev.cancer.gov/develop/foundations/appearance/opacity) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt the opacity tokens within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use opacity tokens without pointing to USWDS
- The community Figma file will be updated to include the opacity tokens
- The NCIDS code will be updated to fully adopt the opacity tokens

### What's the current functionality?
- The doc site directs users to [USWDS](https://designsystem.digital.gov/design-tokens/opacity/) information on how to use opacity tokens

### Related Tickets
* Original story: #1202 
* Related story: #1327

**Comment by dlescarbeau** [comment]
For an approach, I think we should just copy the USWDS table entirely and make a one-off component called OpacityTableDemonstration to show these examples appropriately.

The MDX file wouldn't have any additional example classes as they can all be hard-coded into the component, since it will be specific to the opacity examples. Each class example would just have the `class_name` and the `calculated_value`, with the `class_name` being applied to the example divs.

CC: @bryanpizzillo
