### ISSUE TITLE
GitHub Discussions Review

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1619]
**Description:** We have a number of GH Discussion topics (https://github.com/NCIOCPL/ncids/discussions) that have been recorded following various testing for Redesign. This task is for designers to take a pass through this list and aggregate feedback/comments/recommendations on those that relate to design elements.

**Sub-tasks:**
- [x] Review list of GH Discussions to identify which may have a design impact or are design focused
    - Exclude GH Discussions for which we already discussed in a Requirements meeting (see Canvas notes for this list) 
- [x] Catalogue feedback/comments/recommendations by commenting on the GH Discussion directly
- [ ] Share out

**Comment by blilianyu** [comment]
@laurelthrash I've grouped the discussions below. We can share this out at our Tues/Thurs UX meetings. cc: @monika-jaeger 

### Design Updates
_Note: @monika-jaeger is creating updated images_
- #1370 
  - Update promo blocks to be Annual Plan image and content
  - Update all content on Promo Block page to be "Professional Judgment Budget Proposal" instead of "Annual Plan"
- #1372 
  - Update 2-guide card row pattern image 

### Design Discussions Needed
- #1444 
  - Provided recommendations. Will need to discuss as a team 
- #1604 
  - Will need to discuss with Anna if we want DS to have the option of having no hero image for Home & Landing pages
- #1445 
  - Raw HTML Guide Card Row created ([#4253](https://github.com/NCIOCPL/cgov-digital-platform/issues/4253)) and will be testing out on a landing page and based on analytics will update guidance

### Content Updates
_Will need an IA to provide some language_
- #1602 
- #1603 

### Content Discussions Needed
- #1371 
- #1376
- #1378 
- #1419 
- #1420 
- #1488 

### Confirm Resolution
- #1373 
- #1374 
- #1377
- #1379

**Comment by adrianacastaneda** [comment]
@blilianyu @lburack @laurelthrash  Included two options for the [Banner component](https://designsystem-dev.cancer.gov/develop/components/banner) page description below. 

Not sure if we want to keep it broad and say "all federal websites" because I'm not sure if this is true... So it seems like we could just say that this is required for all websites under NCI. Let me know your thoughts. Thanks!

- A banner used to identify official websites of government organizations in the United States. It allows users to know if a website is both official and secure. This component is required for all NCI informational websites and applications.

- A banner used to identify official websites of government organizations in the United States. It allows users to know if a website is both official and secure. This component is required for all federal websites.

**Comment by blilianyu** [comment]
@adrianacastaneda I prefer Option 1!

**Comment by lburack** [comment]
@adrianacastaneda - USWDS says "most government sites should use the banner." https://designsystem.digital.gov/components/banner/
I don't know if it's mandatory for all federal websites so I think option 1 is your safer bet!

**Comment by laurelthrash** [comment]
We chose to review the discussions that were immediately actionable. These included discussion items under Design Updates, Content Updates, and Confirm Resolution. All of these discussions have either been closed or have a CR created to initiate a solution. 

@andyvanavery31 @sarinapadilla - I propose we close this ticket for the time being as all discussions have received design input. Any concerns with this? All remaining discussion items that are open require further discussion. These discussions include Lilian and Monika's feedback directly on the discussion item so feedback can be discussed in context when the item is picked back up in the future. 

Cc: @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Conferred with @andyvanavery31 @sarinapadilla offline. We will proceed with closing this ticket. All remaining open GH Discussions listed in the description of this ticket contain Lilian and Monika's feedback, to be considered at a later time and tracked via the GH Discussion item. Cc: @blilianyu @monika-jaeger
