### ISSUE TITLE
Develop Common CSS File

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#192]
Develop Common CSS File which will be the basis for the NCI DS, and for many future stories 

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
add @olitharp-nci once she is added to the project

**Comment by bryanpizzillo** [comment]
So some notes from this slog fest.
1. Yes, we really can just reference USWDS partials from our partials and have everything resolve correctly.
2. USWDS actually had to be hoisted to the root for our sanity.
3. Anything using SASS needs the `includePaths` setting that point to the root `node_module` and the package's  `node_modules`. That way they understand where `uswds/blah` and `@nciocpl/ncids-css` live. This applies to `docs` and `ncids-css`. (Although `ncids-css` obviously knows where `@nciocpl/ncids-css` lives)
    ```
    sassOptions: {
      includePaths: [
        path.join(__dirname, 'node_modules'),
        path.join(__dirname, '..', 'node_modules'),
      ],
    },
    ```
4. Gatsby inlines any `url()` url in the CSS. (Unless it is over 10K, then I think the world ends). It does this through the `gatsby-plugin-sass`. All the relative URLs are relative to `docs/src`. USWDS always references `../img` for its image paths. In order to work around this for now, we had to make symlinks for `img` and `fonts` in the `docs` directory that point to uswd.
5. If you set `$theme-image-path: '/public/static/*' !default;` then Gatsby will not inline the images, but this causes issues with the designsystem-dev viewing, cause those sites are `/pr-???` at the beginning.
6. Post CSS can be done on `gatsby-plugin-sass` but `postcss-url` does not work well. 

So now not only is webpack building the CSS, all NCIDS sass can just reference `'uswds/dist/scss/**'` without issues building Gatsby, the big .css file, or any thing else.
