### ISSUE TITLE
Design: Image Carousels

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#209]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Design request:
Design the image carousel component.
##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] We need to keep the optional title field to display on the front end since it is being used (note: video carousels do not have this option currently)
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Assets:
* Mockups: https://publicis.invisionapp.com/share/SY11HI3P4GPR
* Web Page: https://www.cancer.gov/types/skin/moles-fact-sheet

**Comment by blilianyu** [comment]
Need to ask Lynn what the prioritization is since there are only 2 carousels on Cancer.gov before doing design work.
- https://www.cancer.gov/types/skin/moles-fact-sheet
- https://www.cancer.gov/about-cancer/understanding/what-is-cancer]

Anomaly, this page could have a carousel too https://www.cancer.gov/types/skin/mole-photos

**Comment by VictoriaSunNIH** [comment]
Revisit the arrows on carousels
