### ISSUE TITLE
Analytics for Page Options

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#421]
Provide analytics for 
- [ ] Page Options on Desktop (Top and Bottom)

Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:
https://publicis.invisionapp.com/share/MW1112N6286R#/screens/451934895_What_Is_Cancer-

Related Tickets:
- https://github.com/NCIOCPL/cgov-digital-platform/issues/3256

**Comment by nicolecrom** [comment]
Here are the requirements for page options
[Page Options.docx](https://github.com/NCIOCPL/ncids/files/8572106/Page.Options.docx)
One open question we had - will page options be on all pages or only specific page types like articles?

**Comment by VictoriaSunNIH** [comment]
@nicolecrom - page options will appear on any pages that are not home or landing (so basically, all pages except for home and landing pages)

**Comment by nicolecrom** [comment]
Great!

**Requirements Capture**
As a digital analyst, I want to be able to collect information about usage of the site when a user clicks on a link in the page options, so that I can provide product owners insights on how users interact with this element.
_Scenario:_
Given a user is on any page of cancer.gov, other than home or landing pages:
When the user clicks on a link within the page option section at the top or bottom of the page:
Then there should be an NCIDataLayer Other event with the name “PageOptions:LinkClick” and the linkname “PageOptions:LinkClick”
And have the following data:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/cromne/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/cromne/AppData/Local/Temp/1/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/cromne/AppData/Local/Temp/1/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Key | Value
-- | --
linktext | The value   passed should be either “Print” or “Email” depending on which link clicked.
location | Based on if   the link clicked is at the top of the page or the bottom of the page, it   should return either “BodyTop” or “BodyBottom”




</body>

</html>

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3256, so closing this ticket.
