### ISSUE TITLE
Add styling to mobile menu to show current page's location in site structure

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#666]
### Issue description
The mobile menu only uses styling to display a user's current page. We would like to update this to include styling for the user's location in the site structure on higher levels (all the way up to the main menu).

> **ESTIMATE** TBD

### What's the expected change?
- The current page's location in the site structure is conveyed through styling of each of the levels. The current page will get the left horizontal line, while the higher levels will get the blue text (similarly to how the side nav displays).

### What's the current functionality?
- Only the current page has styling.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by meglake** [comment]
Closing per note from Sarina that this is not needed since a decision was made that we didn't want to have the hierarchy of the current page highlighted in the mobile menu, since you don't have the same context that you do on a desktop and having the pages that you're not on highlighted would be confusing.
