### ISSUE TITLE
Spike: Investigate cypress-axe as a replacement for pa11y-ci

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#695]
Investigate the possibility of adding cypress axe 

> **Estimate** *# point* 

### Description
Remove pa11y and add cypress axe to the testing workflow.  Does it raise the same expected issues as pa11y (possibly even more with proper configuration)

### Notes:
https://www.npmjs.com/package/cypress-axe

### Results of Spike

As axe did find some accessibility issues, it would be good to look into this again once the bugs are addressed in cypress axe. Adding axe as a runner in addition to HTML code sniffer may work for our needs. It may even be worthwhile keeping both pa11y-ci and cypress axe instead of just one. Detailed findings below.

**Comment by olitharp-nci** [comment]
### Findings 

#### pa11y-ci

pa11y-ci with htmlcs runner (WCAG2AA):
```bash
Running Pa11y on 11 URLs:
 > http://localhost:8080/data/mega-menu/example-data-1.html - 2 errors
 > http://localhost:8080/data/mega-menu/example-data-2.html - 2 errors
 > http://localhost:8080/data/mega-menu/example-data-3.html - 2 errors
 > http://localhost:8080/data/mega-menu/example-data-4.html - 2 errors
 > http://localhost:8080/data/mega-menu/example-data-5.html - 2 errors
 > http://localhost:8080/example-pages/cgov-home.html - 0 errors
 > http://localhost:8080/example-pages/landing-page.html - 0 errors
 > http://localhost:8080/example-pages/microsite-home.html - 0 errors
 > http://localhost:8080/index.html - 0 errors
 > http://localhost:8080/inner-pages/inner-page.html - 0 errors
 > http://localhost:8080/inner-pages/multiple-autocomplete-fields.html - 0 errors
```
Note: data/mega-menu/example pages error on 
* A title should be provided for the document, using a non-empty title element in the head section.
* The html element should have a lang or xml:lang attribute which describes the language of the document.

But these files can ignore this error as they are part of another page

pa11y-ci with htmlcs and axe runner runner (WCAG2AA):

```bash
Running Pa11y on 11 URLs:
 > http://localhost:8080/data/mega-menu/example-data-1.html - 5 errors
 > http://localhost:8080/data/mega-menu/example-data-2.html - 5 errors
 > http://localhost:8080/data/mega-menu/example-data-3.html - 5 errors
 > http://localhost:8080/data/mega-menu/example-data-4.html - 5 errors
 > http://localhost:8080/data/mega-menu/example-data-5.html - 5 errors
 > http://localhost:8080/example-pages/cgov-home.html - 5 errors
 > http://localhost:8080/example-pages/landing-page.html - 5 errors
 > http://localhost:8080/example-pages/microsite-home.html - 5 errors
 > http://localhost:8080/index.html - 2 errors
 > http://localhost:8080/inner-pages/inner-page.html - 3 errors
 > http://localhost:8080/inner-pages/multiple-autocomplete-fields.html - 3 errors
```

In addition to the note above, these error include:
* Elements must have sufficient color contrast
  * Note: errored elements found pass AA, but not AAA, even when WCAG2AA is set. **Is this pa11y-ci or axe?**
* ARIA hidden element must not be focusable or contain focusable elements
  * This might be a real error found via axe
* Elements must only use allowed ARIA attributes
  * real error - **fixed on cgov but not fixed in example site yet** 

#### cypress axe

Issues with installing -

```bash
AssertionError: Timed out retrying after 4000ms: `cy.readFile("node_modules/axe-core/axe.min.js")` failed because the file does not exist at the following path:

`ncids/testing/ncids-js-testing/node_modules/axe-core/axe.min.js`
```

Looks to be some kinks in the package, see https://github.com/component-driven/cypress-axe issues 73, 84, and 134.

PR 150 may fix the issue.

**Comment by bennettcc** [comment]
Findings on cypress-axe were documented on this ticket - marking as complete
