### ISSUE TITLE
Some documentation site examples changed with USWDS 3.0

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#832]
### Issue description
> **ESTIMATE** TBD

As part of the wide changes for USWDS we had to update the documentation site's index.scss. As such, a number of things were removed causing issues on the font design-tokens page.

* Bad: https://designsystem-dev.cancer.gov/develop/design-tokens/typography/fonts#font-weight-tokens
* Good: https://designsystem-dev.cancer.gov/v1.3.0/design-tokens/typography/fonts#font-weight-tokens

**Comment by olitharp-nci** [comment]
Bryan and I did some investigating, adding our findings here for whenever we pick this up again

1. Turn on all font utility classes
    ```scss
	$font-palettes: ("palette-font"),
	$font-weight-palettes: ("palette-font-weight"),
    ```
2. Add missing font imports
    ```scss
    @import 'uswds/dist/scss/packages/usa-table';
    @import './scss/uswds-site.scss';
    @import './scss/markdown-heading';
    @import './scss/inline-code';
    ```
    Note the above code was copy pasta'd from [v1.3.0](https://github.com/NCIOCPL/ncids/blob/v1.3.0/docs/src/index.scss) and should be updated with @forwards
    
3. The above [`uswds-site.scss`](https://github.com/NCIOCPL/ncids/blob/v1.3.0/docs/src/scss/uswds-site.scss) file was just completely deleted and needs to be brought back -- because apparently when I update things, ripping things out brings me joy.
