### ISSUE TITLE
NCIDS For All Pilot - Contact Information

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#947]
## As anyone who uses NCIDS For All, I want to know who I can contact if I have questions or want to contribute, so that I know how to use the system and report errors.

> **ESTIMATE** TBD

**Comment by bennettcc** [comment]
@sarinapadilla @andyvanavery - for this story, are we providing the contact information to USWDS?  Or contact information for the OCPL team?

If it's the OCPL team, this story may not be needed since Pilot (and future adopters) user will have lots of documentation + Teams spaces with us. I assume this ticket is referring to us since DOC users would come to us with questions (to then maybe pass along to USWDS)

**Comment by bennettcc** [comment]
Closing this ticket - we're including ODDC Teams contact information on the Pilot documentation site
